### ISSUE TITLE
Does not work with 32-bit BMP files

### ISSUE THREAD

**Issue by erikmartinessanches** [hoiberg/bitmapToC#1]
Problems with a 32-bit BMP, size 128x32px, created in GIMP. Nothing appears when I hit "Convert". Attaching the images. Should the image perhaps be runlength encoded or something?
![screenshot 2018-02-18_21-31-05](https://user-images.githubusercontent.com/4912935/36356494-11a4daa0-14f3-11e8-813f-7b21933658b4.png)
[tennis.bmp.zip](https://github.com/hoiberg/bitmapToC/files/1735095/tennis.bmp.zip)

**Comment by hoiberg** [comment]
It only works with BMP files with one bit per pixel (as stated in the readme). 

If you have Photoshop, open the BMP and set to Black & White mode, then to Bitmap mode, then save it with the 1 bit per pixel setting. I don't know how to do this with GIMP.
